spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"

error-manager:
  enabled: true


connectors:
  jdbcConfigurations:
    default:
      connectionPoolSize: 5
      timeout: 30000
      mocked: false
    items:
      GetCountriesJdbcConnector:
        uri: ${DATASOURCE_URL}
        driver-class-name: org.postgresql.Driver
        username: ${DATASOURCE_USER}
        password: ${DATASOURCE_PWD}


  jpaConfigurations:
    connection:
      url: ${DATASOURCE_URL}
      driver-class-name: org.postgresql.Driver
      username: ${DATASOURCE_USER}
      password: ${DATASOURCE_PWD}
      connectionPoolSize: 5
      timeout: 30000
      mocked: false
      hbm2ddl: none
      hibernateDialect: org.hibernate.dialect.Oracle10gDialect
    repositories:
      - jpaRepository



#### Security configuration
keycloak:
  enabled: false
  auth-server-url:
  resource:
  realm:
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  bearer-only: true
  autodetect-bearer-only: true
  token-store: cookie
  security-constraints:
    - auth-roles:
        - openid
      security-collections:
        - name: reserved
          patterns:
            - /*


listeners:
  eventConfigurations:
    items:
      KafkaConnectoriListner:
        bootstrapServers: ${KAFKA_STRATEGIA_BROKERS}
        topic: ${KAFKA_TOPIC_DEMO}
        groupId: ${KAFKA_STRATEGIA_GROUPID}
        clientId: DEMO
        concurrency: 3
        enable.auto.commit: true
        max.poll.records: 10
        security:
          protocol: ${KAFKA_STRATEGIA_SECURITY_PROTOCOL}
        sasl:
          kerberos:
            service:
              name: ${KAFKA_STRATEGIA_SERVICE_NAME:xx}
          jaas:
            config: "com.sun.security.auth.module.Krb5LoginModule required
            useKeyTab=true keyTab=\"${KEYTAB_STRATEGIA_KERB_FILE_PATH}\"
            principal=\"${KEYTAB_STRATEGIA_KERB_USERNAME}@${KEYTAB_STRATEGIA_KERB_REALM_DOMAIN}\";"